WebApp/Models/BestRestaurantsContext.cs
using Microsoft.EntityFrameworkCore;

namespace BestRestaurants.Models
{
  public class BestRestaurantsContext : DbContext
  {
    public virtual DbSet<Cuisine> Cuisines { get; set; }
    public DbSet<Restaurant> Restaurants { get; set; }
    public DbSet<RestaurantImage> Images { get; set; }
    public BestRestaurantsContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

WebApp/Models/Cuisine.cs
using System.Collections.Generic;

namespace BestRestaurants.Models
{
  public class Cuisine
  {
    public Cuisine()
    {
      this.Restaurants = new HashSet<Restaurant>();
    }
    public int CuisineId { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public virtual ICollection<Restaurant> Restaurants { get; set; }

  }
}

WebApp/Models/Cuisines.cs
using System.Collections.Generic;

namespace BestRestaurants.Models
{
  public class Cuisine
  {
    public Cuisine()
    {
      this.Restaurants = new HashSet<Restaurant>();
    }
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public virtual ICollection<Restaurant> Restaurants { get; set; }

  }
}

WebApp/Models/Restaurant.cs
using System.Collections.Generic;
namespace BestRestaurants.Models
{
  public class Restaurant
  {
    public Restaurant()
    {
      this.Images = new HashSet<RestaurantImage>();
    }
    public int Id { get; set; }
    public string Name { get; set; }
    public string Address { get; set; }
    public string Phone { get; set; }
    public int CuisineId { get; set; }
    public virtual Cuisine Cuisine { get; set; }
    public virtual ICollection<RestaurantImage> Images { get; set; }
  }
}

WebApp/Models/RestaurantImage.cs
namespace BestRestaurants.Models
{
  public class RestaurantImage
  {
    public int Id { get; set; }
    public int RestaurantId { get; set; }

    public byte[] Image { get; set; }
    public string ImageString { get; set; }
  }
}

WebApp/Models/Restaurants.cs
namespace BestRestaurants.Models
{
  public class Restaurant
  {
    public int Id { get; set; }
    public string Name { get; set; }
    public string Address { get; set; }
    public string Phone { get; set; }
    public virtual Cuisine Cuisine { get; set; }
  }
}

WebApp/Controllers/CuisinesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;

namespace BestRestaurants.Controllers
{
  public class CuisinesController : Controller
  {
    private readonly BestRestaurantsContext _db;

    public CuisinesController(BestRestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Cuisine> model = _db.Cuisines.ToList();
      return View(model);
    }

    public ActionResult Details(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }
  }
}

WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace BestRestaurants.Controllers
{
  public class HomeController : Controller
  {

    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }

  }
}

WebApp/Controllers/RestaurantImagesController.cs
using Microsoft.AspNetCore.Mvc;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using System;
namespace BestRestaurants.Controllers
{
  public class RestaurantImageController : Controller
  {
    private readonly BestRestaurantsContext _db;

    public RestaurantImageController(BestRestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Create(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.Id == id);
      return View(thisRestaurant);
    }

    [HttpPost]
    public IActionResult Upload(IFormFile file)
    {
      Console.WriteLine(file);
      return Ok();
    }

  }
}

WebApp/Controllers/RestaurantsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BestRestaurants.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Http;



namespace BestRestaurants.Controllers
{
  public class RestaurantsController : Controller
  {
    private readonly BestRestaurantsContext _db;

    public RestaurantsController(BestRestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Restaurant> model = _db.Restaurants.Include(restaurant => restaurant.Cuisine).ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Restaurant restaurant)
    {

      _db.Restaurants.Add(restaurant);
      _db.SaveChanges();
      return RedirectToAction("Upload", new { id = restaurant.Id });
    }

    public ActionResult Upload(int id)
    {

      ViewBag.thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.Id == id);
      return View();
    }

    [HttpPost]
    public ActionResult Upload(IFormFile file, int id)
    {
      Console.Write(id);
      using (var ms = new MemoryStream())
      {
        file.CopyTo(ms);
        var fileBytes = ms.ToArray();
        RestaurantImage newImage = new RestaurantImage();
        string s = Convert.ToBase64String(fileBytes);
        newImage.ImageString = s;
        newImage.RestaurantId = id;
        _db.Images.Add(newImage);
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }


    public ActionResult Details(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.Id == id);
      ViewBag.Cuisine = thisRestaurant.Cuisine;
      return View(thisRestaurant);
    }

    public ActionResult Edit(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.Id == id);
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View(thisRestaurant);
    }

    [HttpPost]
    public ActionResult Edit(Restaurant restaurant)
    {
      _db.Entry(restaurant).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.Id == id);
      return View(thisRestaurant);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.Id == id);
      _db.Restaurants.Remove(thisRestaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

  }

}

WebApp/Views/Cuisines/Details.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models;
@model BestRestaurants.Models.Cuisine;

<div class="main">
  <h1>@Html.DisplayFor(model => model.Name)</h1>

  <ul>
    @foreach (Restaurant restaurant in @Model.Restaurants)
    {
      <li>@Html.ActionLink($"{restaurant.Name}", "Details", "Restaurants", new { id = restaurant.Id })</li>
    }
  </ul>
</div>

WebApp/Views/Cuisines/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models;
@model List<BestRestaurants.Models.Cuisine>;

<div class="main">
  <h1>Cuisines</h1>

  <p>You came to the right place. Slake your hunger with a restaurant in the cuisine you're craving.</p>
  <ul>
    @foreach (Cuisine cuisine in Model)
    {
      <li>@Html.ActionLink($"{cuisine.Name}", "Details", new { id = cuisine.CuisineId })</li>
    }
  </ul>
</div>

WebApp/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<div class="main">
  <div id="splash">
    <h3>Welcome to Best Restaurants!</h3>
    <p>Inside, you'll find the best restaurants near you, created and submitted by people like you.</p>
  </div>

  <h1 id="get-started">@Html.ActionLink("Get started", "Index", "Cuisines")</h1>

</div>

WebApp/Views/RestaurantImages/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant

<div class="main">
  <h4>Add a new picture</h4>
  <form enctype="multipart/form-data" method="post" action="/RestaurantImages/upload">
    <input type="file" name="file" />
    <input type="submit" />
  </form>

</div>

WebApp/Views/Restaurants/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant
@using BestRestaurants.Models
<div class="main">
  <h4>Add a new restaurant</h4>
  @using (Html.BeginForm())
  {
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    @Html.LabelFor(model => model.Address)
    @Html.TextBoxFor(model => model.Address)
    @Html.LabelFor(model => model.Phone)
    @Html.TextBoxFor(model => model.Phone)

    @Html.LabelFor(model => model.Cuisine)
    @Html.DropDownList("CuisineId")

    <input type="submit" value="Add" />

  }

</div>

WebApp/Views/Restaurants/Delete.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant

<div class="main">
  <h2>Are you sure you want to delete @Model.Name?</h2>

  @using (Html.BeginForm())
  {
    <button type="submit" value="Delete">Confirm</button>
  }
</div>

WebApp/Views/Restaurants/Details.cshtml
@model BestRestaurants.Models.Restaurant
@using BestRestaurants.Models
@{
  Layout = "_Layout";
}

<div class="main">
  <h1>@Model.Name</h1>

  <h3>Address: @Model.Address</h3>
  <h3>Phone: @Model.Phone</h3>
  <h3>Cuisine: @Model.Cuisine.Name</h3>
  @foreach (RestaurantImage i in Model.Images)
  {
    <img src="data:image;base64,@i.ImageString" width="auto" height="80" />
  }
  <p class="edit-link">@Html.ActionLink("Edit Restaurant", "Edit", new {id = Model.Id})</p>
  <p class="delete-link">@Html.ActionLink("Delete Restaurant", "Delete", new {id = Model.Id})</p>
</div>

WebApp/Views/Restaurants/Edit.cshtml
@{
  Layout = "_Layout";
}
@model BestRestaurants.Models.Restaurant

<div class="main">
  <h2>Edit @Model.Name</h2>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.Id)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)
    @Html.LabelFor(model => model.Address)
    @Html.EditorFor(model => model.Address)
    @Html.LabelFor(model => model.Phone)
    @Html.EditorFor(model => model.Phone)

    @Html.DropDownList("CuisineId")

    <input type="submit" value="Save" />

  }
  @Html.ActionLink("Add Picture", "Upload", new {id = @Model.Id})
</div>

WebApp/Views/Restaurants/Index.cshtml
@{
  Layout = "_Layout";
}

<div class="main">
  <h1>Restaurants</h1>

  @using BestRestaurants.Models;
  @model List<BestRestaurants.Models.Restaurant>;

  @if (@Model.Count == 0)
  {
    <h3>No restaurants have been added yet...</h3>
  }

  @foreach (Restaurant restaurant in Model)
  {
    <li>@Html.ActionLink($"{restaurant.Name}", "Details", new { id = restaurant.Id}): @restaurant.Cuisine.Name</li>
  }
  <p>@Html.ActionLink("Add new restaurant", "Create")</p>
</div>

WebApp/Views/Restaurants/Upload.cshtml
@{
  Layout = "_Layout";
  var restaurant = ViewBag.thisRestaurant as Restaurant;
}
@using BestRestaurants.Models;
@model BestRestaurants.Models.RestaurantImage

<div class="main">
  <h4>Add a new picture</h4>
  <h1>@restaurant.Name</h1>
  <form enctype="multipart/form-data" method="post" action="upload">
    <input type="file" name="file" />
    <input type="hidden" name="id" value="@restaurant.Id" />
    <input type="submit" />
  </form>
  @Html.ActionLink("Skip", "Index")
</div>

WebApp/Views/Shared/Footer.cshtml
@Html.ActionLink("Return home", "Index", "Home")
@Html.ActionLink("See all restaurants", "Index", "Restaurants")
@Html.ActionLink("See all cuisines", "Index", "Cuisines")

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Best Restaurants</title>
  <link rel="stylesheet" href="~/css/styles.css">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link
    href="https://fonts.googleapis.com/css2?family=Cantarell&family=Oleo+Script:wght@700&family=Spinnaker&display=swap"
    rel="stylesheet">
</head>

<header>
  <h1>Best Restaurants</h1>
</header>

<body>
  @RenderBody()
</body>

<footer>
  @await Html.PartialAsync("Footer")
</footer>

</html>